/** Стабильные подписи ruleId для отчётов (русский). */
export const RULE_LABELS: Record<string, string> = {
  title_present: "Некорректное или короткое название",
  title_not_generic: "Слишком общее название",
  description_present: "Нет или короткое описание",
  description_has_goal: "Нет цели в описании",
  assignee_present: "Нет исполнителя",
  blocked_assignee_not_allowed:
    "Задача не назначена на заблокированного/неактивного пользователя",
  assignee_not_in_users_list:
    "Исполнитель найден в списке пользователей AppTask",
  deadline_present: "Нет дедлайна",
  deadline_not_overdue: "Просроченный дедлайн",
  deadline_start_not_after_due: "Дата начала позже дедлайна",
  deadline_realistic: "Нереалистичный срок",
  priority_present: "Нет приоритета",
  tags_required: "Обязательные теги",
  task_type_valid: "Некорректный тип задачи",
  stage_matches_column: "Этап не соответствует статусу",
  estimate_present: "Нет оценки времени/бюджета",
  estimate_link_present: "Нет ссылки на смету/договор",
  artifact_links_present: "Нет ссылок на артефакты",
  links_reachable: "Проблемы со ссылками",
  not_duplicate: "Возможный дубликат",
  unresolved_question_keywords_in_card:
    "Есть признак незакрытого вопроса",
  open_questions_closed: "Открытый вопрос в комментариях без ответа",
  review_stage_requires_assignee:
    "На этапе проверки назначен тестировщик",
  scrum_task_in_estimate: "Задача не найдена в утверждённой смете",
  scrum_title_matches_estimate: "Название не совпадает со сметой",
  scrum_planned_hours_present: "ПВ («Оценка (ч)») не указано в смете",
  scrum_decomposition_over_20h: "Задача >20 ч без декомпозиции",
  deadline_less_than_one_day: "До дедлайна меньше суток",
  blocked_task_reason: "Блокировка без причины",
  review_queue_over_limit: "Очередь на тестирование > лимита",
  in_progress_stale: "В процессе без обновлений",
  review_stale: "На проверке без движения",
  vague_done_comment: "Комментарий «готово» без деталей",
  high_priority_stale: "Высокий приоритет без движения",
  rework_without_reason: "Возврат на доработку без причины",
  done_task_without_tracking: "Завершена без фактического времени",
  in_progress_without_recent_tracking: "В работе без трекинга за раб. день",
  actual_hours_exceeds_estimate: "Факт > ПВ (+порог)",
  estimate_exceeded_without_comment: "Перерасход ПВ без комментария",
  tracking_on_non_work_status: "Трекинг вне рабочего статуса",
  blocked_tag_present: "Нет тега blocked у заблокированной задачи",
  developer_active_tasks_limit: "Слишком много активных задач у исполнителя",
  never_started_task: "Задача давно создана, но не брали в работу",
  board_name_template: "Название доски не по шаблону",
  board_folder_link: "Нет ссылки на папку проекта в описании доски",
  board_tz_summary: "Нет краткого описания проекта из ТЗ",
  project_worksheet_match:
    "Название и описание проекта не сверены с рабочей таблицей",
  team_worksheet_match: "Участник не найден в рабочей таблице",
  team_discord_match: "Участник не найден в Discord",
  team_role_rate_match: "Роль или ставка не заполнены в рабочей таблице",
  task_type_classification: "Задачи не классифицированы по типам",
  sprint_dates_match: "Даты спринтов не сверены со Scrum",
  ui_has_mockup_link: "Нет ссылки на макет (UI)",
  ui_mockup_approved: "Макет не согласован перед разработкой",
  ui_adaptive_requirements: "Нет требований к адаптивности",
  ui_browser_device_requirements: "Нет требований к браузерам/устройствам",
  tracking_daily_anomaly: "Аномально большое списание за день",
  tracking_high_without_result: "Много часов без результата/комментариев",
  verified_success_comment: "Нет комментария «проверено»",
  tester_feedback_has_proof: "Замечания тестировщика без пруфа",
  mass_start_without_completion: "Массовый старт без завершения старых задач",
  act_ready_naming: "Название задачи не готово для акта",
};

export function ruleLabel(ruleId: string): string {
  return RULE_LABELS[ruleId] ?? ruleId;
}
