import { CONTRACT_CHECK_REGISTRY } from "./contract-check-registry.js";
import type { AutomationLevel } from "../rules/evidence-types.js";

/** Статусы, распознаваемые как QA / review (см. также TESTING_STATUS_RE). */
export const REVIEW_STATUS_ALIASES = [
  "На проверке",
  "Проверить тестировщику",
  "QA",
  "Review",
  "Тестирование",
  "Проверка",
  "testing",
  "review",
  "qa",
] as const;

export type ContractRuleEvidenceSpec = {
  num: number;
  title: string;
  ruleIds: readonly string[];
  sources: string;
  scope: string;
  candidates: string;
  violation: string;
  passed: string;
  notChecked: string;
  outcomeOK: string;
  outcomePartial: string;
  outcomeSkip: string;
  automationLevel: AutomationLevel;
  /** «да» | «частично» | «нет» — можно ли доказать автоматически. */
  autoProvable: string;
  /** Подсказка для формулировок в отчёте при не-STRICT уровне. */
  reportWording?: string;
};

const EVIDENCE_BY_NUM: Record<number, Omit<ContractRuleEvidenceSpec, "num" | "title" | "ruleIds">> = {
  1: {
    sources: "AppTask DB: deadline/dueDate, status",
    scope: "активные task-level карточки (не потоковые)",
    candidates: "не завершены; дедлайн задан; до дедлайна < 24 ч",
    violation: "candidate не завершён и дедлайн < 24 ч (WARN) или просрочен (FAIL)",
    passed: "candidates без нарушения (нет таких задач в зоне < 24 ч)",
    notChecked: "—",
    outcomeOK: "candidates = 0 → «Кандидатов для проверки нет»; не писать «64 кандидатов»",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  2: {
    sources: "AppTask task id/title; Scrum / утверждённая смета",
    scope: "task-level карточки",
    candidates: "все карточки при доступной смете",
    violation: "задача не найдена в утверждённой смете",
    passed: "задача найдена в смете",
    notChecked: "Scrum / смета недоступна",
    outcomeOK: "все задачи в смете",
    outcomePartial: "—",
    outcomeSkip: "смета не загружена",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  3: {
    sources: "AppTask tags, status/stage (blocked)",
    scope: "заблокированные task-level карточки",
    candidates: "статус/этап содержит blocked / блокер",
    violation: "нет тега blocked/блок",
    passed: "тег blocked присутствует",
    notChecked: "—",
    outcomeOK: "0 заблокированных → «Кандидатов для проверки нет»",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  4: {
    sources: "AppTask comments, status (blocked)",
    scope: "заблокированные task-level карточки",
    candidates: "заблокированные задачи",
    violation: "нет причины блокировки в комментариях (фиксированные маркеры)",
    passed: "есть комментарий с причиной",
    notChecked: "—",
    outcomeOK: "0 заблокированных",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по фиксированным маркерам причины блокировки",
  },
  5: {
    sources: "AppTask descriptionText",
    scope: "task-level карточки",
    candidates: "все карточки",
    violation: "описание пустое или короче порога (80 символов)",
    passed: "описание заполнено",
    notChecked: "—",
    outcomeOK: "все с описанием",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  6: {
    sources: "Scrum ПВ; структура подзадач AppTask",
    scope: "task-level карточки с ПВ > 20 ч в смете",
    candidates: "строки сметы с ПВ > 20 ч",
    violation: "нет декомпозиции (подзадач / дочерних)",
    passed: "декомпозировано",
    notChecked: "строка не в смете или Scrum недоступен",
    outcomeOK: "0 задач с ПВ > 20 ч",
    outcomePartial: "часть задач без строки сметы",
    outcomeSkip: "Scrum недоступен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  7: {
    sources: "AppTask project metadata; Google Sheet / рабочая таблица",
    scope: "проект (entity-level)",
    candidates: "один проект",
    violation: "расхождение названия или описания с таблицей",
    passed: "совпадает с таблицей",
    notChecked: "таблица недоступна",
    outcomeOK: "совпадение",
    outcomePartial: "—",
    outcomeSkip: "таблица не загружена",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  8: {
    sources: "AppTask users; Google Sheet; Discord guild (опционально)",
    scope: "команда проекта (entity-level)",
    candidates: "участники AppTask vs таблица (+ Discord подисточник)",
    violation: "участник есть в одном источнике, нет в другом",
    passed: "состав совпадает",
    notChecked: "Discord недоступен → подисточник SKIP",
    outcomeOK: "состав совпадает",
    outcomePartial: "Discord не проверен, таблица проверена",
    outcomeSkip: "таблица недоступна",
    automationLevel: "PARTIAL",
    autoProvable: "частично",
    reportWording: "Discord — отдельный подисточник; при недоступности не FAIL",
  },
  9: {
    sources: "AppTask assignees; Google Sheet (роль, ставка)",
    scope: "исполнители из рабочей таблицы",
    candidates: "участники, найденные в таблице",
    violation: "роль или ставка не совпадает",
    passed: "роль и ставка совпадают",
    notChecked: "исполнитель не найден в таблице (роль/ставку сверить нельзя)",
    outcomeOK: "все в таблице совпали",
    outcomePartial: "есть исполнители без строки в таблице → WARN + «Не проверено»",
    outcomeSkip: "таблица недоступна",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  10: {
    sources: "AppTask sprints; Scrum sprint dates",
    scope: "спринты проекта (entity-level)",
    candidates: "спринты в AppTask и Scrum",
    violation: "расхождение дат или названий",
    passed: "даты и названия совпадают",
    notChecked: "Scrum недоступен",
    outcomeOK: "совпадение",
    outcomePartial: "—",
    outcomeSkip: "Scrum не загружен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  11: {
    sources: "AppTask tags, category, title, description",
    scope: "task-level карточки",
    candidates: "все карточки",
    violation: "тип не определён или не из allowed list",
    passed: "тип классифицирован",
    notChecked: "—",
    outcomeOK: "все классифицированы",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  12: {
    sources: "AppTask title; Scrum / смета",
    scope: "task-level карточки в смете",
    candidates: "задачи с найденной строкой сметы",
    violation: "название AppTask ≠ смета",
    passed: "названия совпадают",
    notChecked: "строка сметы не найдена",
    outcomeOK: "совпадения",
    outcomePartial: "часть без строки сметы",
    outcomeSkip: "Scrum недоступен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  13: {
    sources: "AppTask task id/title; Scrum / смета (ПВ)",
    scope: "task-level карточки",
    candidates: "задачи, найденные в Scrum / смете",
    violation: "строка сметы найдена, но ПВ пустое / 0",
    passed: "ПВ указано",
    notChecked: "задача не найдена в смете (ПВ не проверялось)",
    outcomeOK: "все в смете с ПВ",
    outcomePartial: "notChecked > 0 → PARTIAL + кнопка «Не проверено: N»",
    outcomeSkip: "Scrum / смета недоступна",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  14: {
    sources: "AppTask priority, status, activity/history",
    scope: "task-level high priority / critical bug",
    candidates: "high priority или critical bug, не завершены",
    violation: "нет движения > 24 ч",
    passed: "есть активность",
    notChecked: "—",
    outcomeOK: "0 high priority / critical bug",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  15: {
    sources: "AppTask status, comments, history",
    scope: "task-level «в работе»",
    candidates: "статус «в процессе / в работе», не завершены",
    violation: "нет обновлений > 2 рабочих дней",
    passed: "есть недавняя активность",
    notChecked: "—",
    outcomeOK: "0 задач в работе без обновлений",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  16: {
    sources: "AppTask DB current status; status history",
    scope: "task-level карточки",
    candidates: "текущий статус ∈ review/QA aliases",
    violation: "candidate без движения > 1 рабочего дня",
    passed: "есть движение или срок не превышен",
    notChecked: "—",
    outcomeOK: "candidates = 0 → показать aliases + распределение статусов + «текущих на проверке: 0»",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  17: {
    sources: "AppTask board metrics (очередь QA)",
    scope: "доска / агрегат",
    candidates: "текущая очередь на проверке",
    violation: "очередь > лимита (10)",
    passed: "очередь в пределах лимита",
    notChecked: "—",
    outcomeOK: "0 задач на проверке или ≤ лимита",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  18: {
    sources: "AppTask assignees",
    scope: "активные task-level карточки",
    candidates: "карточки без исполнителя",
    violation: "исполнитель не назначен",
    passed: "исполнитель есть",
    notChecked: "—",
    outcomeOK: "0 без исполнителя",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  19: {
    sources: "AppTask description links; классификация UI/front",
    scope: "UI/front task-level карточки",
    candidates: "классифицированные UI/front задачи",
    violation: "нет ссылки на макет",
    passed: "ссылка на макет есть",
    notChecked: "—",
    outcomeOK: "0 UI/front задач или все с макетом",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  20: {
    sources: "AppTask description / comments",
    scope: "UI/front task-level карточки",
    candidates: "UI/front с макетом",
    violation: "нет маркера согласования макета",
    passed: "макет согласован (маркер найден)",
    notChecked: "—",
    outcomeOK: "маркеры согласования найдены или 0 UI задач",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по фиксированным маркерам согласования",
  },
  21: {
    sources: "AppTask description / comments",
    scope: "UI/front task-level карточки",
    candidates: "UI/front задачи",
    violation: "нет требований к адаптивности",
    passed: "требования найдены",
    notChecked: "—",
    outcomeOK: "0 UI задач или требования есть",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по ключевым словам адаптивности",
  },
  22: {
    sources: "AppTask description / comments",
    scope: "UI/front task-level карточки",
    candidates: "UI/front задачи",
    violation: "нет требований к браузерам/устройствам",
    passed: "требования найдены",
    notChecked: "—",
    outcomeOK: "0 UI задач или требования есть",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по ключевым словам браузеров/устройств",
  },
  23: {
    sources: "AppTask status; tracking DB",
    scope: "активные «в работе» task-level",
    candidates: "в работе без трекинга за последние N ч",
    violation: "нет недавнего трекинга",
    passed: "трекинг есть",
    notChecked: "tracking недоступен",
    outcomeOK: "все в работе с трекингом",
    outcomePartial: "—",
    outcomeSkip: "tracking не загружен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  24: {
    sources: "AppTask status; tracking DB (24 ч)",
    scope: "task-level карточки",
    candidates: "задачи с трекингом за 24 ч",
    violation: "трекинг вне рабочего статуса",
    passed: "трекинг только в рабочем статусе",
    notChecked: "tracking недоступен",
    outcomeOK: "0 записей трекинга за 24 ч",
    outcomePartial: "—",
    outcomeSkip: "tracking не загружен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  25: {
    sources: "Tracking факт; Scrum ПВ",
    scope: "task-level с ПВ в смете",
    candidates: "задачи с фактом и ПВ",
    violation: "факт > ПВ + 20%",
    passed: "факт в пределах",
    notChecked: "нет ПВ или tracking",
    outcomeOK: "нет превышений",
    outcomePartial: "часть без ПВ",
    outcomeSkip: "источник недоступен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  26: {
    sources: "Tracking факт; Scrum ПВ; AppTask comments",
    scope: "задачи с превышением ПВ",
    candidates: "превышение ПВ > порога",
    violation: "нет комментария-объяснения",
    passed: "комментарий есть",
    notChecked: "—",
    outcomeOK: "0 превышений или все с комментарием",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "превышение — STRICT; комментарий — по маркерам",
  },
  27: {
    sources: "Tracking DB (user-day aggregate)",
    scope: "user-day (включая потоковые в факте)",
    candidates: "дни с суммарным списанием > лимита",
    violation: "аномальное списание за день",
    passed: "в пределах лимита",
    notChecked: "tracking недоступен",
    outcomeOK: "анomalies = 0",
    outcomePartial: "—",
    outcomeSkip: "tracking не загружен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  28: {
    sources: "AppTask status; tracking факт",
    scope: "завершённые task-level",
    candidates: "завершённые задачи",
    violation: "фактическое время = 0",
    passed: "факт > 0",
    notChecked: "tracking недоступен",
    outcomeOK: "нет завершённых с нулевым трекингом",
    outcomePartial: "—",
    outcomeSkip: "tracking не загружен",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  29: {
    sources: "Tracking DB; AppTask comments / status",
    scope: "task-level с большим трекингом",
    candidates: "трекинг > порога без результата",
    violation: "нет комментария/результата",
    passed: "есть результат или комментарий",
    notChecked: "—",
    outcomeOK: "0 кандидатов",
    outcomePartial: "—",
    outcomeSkip: "tracking недоступен",
    automationLevel: "PARTIAL",
    autoProvable: "частично",
    reportWording: "«результат» определяется по статусу и комментариям",
  },
  30: {
    sources: "AppTask status, assignees",
    scope: "разработчики (агрегат по исполнителю)",
    candidates: "исполнители с активными задачами в работе",
    violation: "> 3 активных задач",
    passed: "≤ 3 активных",
    notChecked: "—",
    outcomeOK: "0 исполнителей с превышением",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  31: {
    sources: "AppTask board metrics (очередь QA)",
    scope: "доска / агрегат (дубликат №17 для контракта)",
    candidates: "текущая очередь на проверке",
    violation: "очередь > 10",
    passed: "очередь ≤ 10",
    notChecked: "—",
    outcomeOK: "0 на проверке или ≤ 10",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  32: {
    sources: "AppTask status history, assignees",
    scope: "исполнители (агрегат)",
    candidates: "исполнители с недавним массовым стартом",
    violation: "старт новых без завершения старых",
    passed: "нет массового старта",
    notChecked: "—",
    outcomeOK: "0 исполнителей в зоне проверки",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  33: {
    sources: "AppTask comments; status history",
    scope: "завершённые после успешной проверки",
    candidates: "завершённые с историей проверки",
    violation: "нет комментария «проверено»",
    passed: "комментарий найден",
    notChecked: "—",
    outcomeOK: "0 завершённых без «проверено»",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по маркеру «проверено»",
  },
  34: {
    sources: "AppTask comments (замечания тестировщика)",
    scope: "карточки с rework / замечаниями QA",
    candidates: "комментарии-требования доработки",
    violation: "нет скрина/видео/ссылки",
    passed: "доказательство есть",
    notChecked: "—",
    outcomeOK: "0 замечаний без proof",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "proof — по URL/вложениям в комментарии",
  },
  35: {
    sources: "AppTask status history; comments",
    scope: "переходы на доработку",
    candidates: "переходы review → in progress / rework",
    violation: "нет причины в комментарии",
    passed: "причина указана",
    notChecked: "—",
    outcomeOK: "0 rework без причины",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "причина — по маркерам в комментарии",
  },
  36: {
    sources: "AppTask comments",
    scope: "task-level карточки",
    candidates: "комментарии с маркерами «готово/сделал/проверь»",
    violation: "маркер без деталей",
    passed: "детали есть или маркеров нет",
    notChecked: "—",
    outcomeOK: "0 найденных маркеров",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по фиксированным маркерам vague done",
  },
  37: {
    sources: "AppTask createdAt; status history",
    scope: "task-level карточки",
    candidates: "созданы > N дней назад, не завершены, не брались в работу",
    violation: "никогда не переходили в работу",
    passed: "были в работе",
    notChecked: "—",
    outcomeOK: "0 старых без старта",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  38: {
    sources: "AppTask board metadata",
    scope: "доска (entity-level)",
    candidates: "название доски",
    violation: "не соответствует шаблону",
    passed: "шаблон соблюдён",
    notChecked: "метаданные доски недоступны",
    outcomeOK: "шаблон OK",
    outcomePartial: "—",
    outcomeSkip: "метаданные недоступны",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  39: {
    sources: "AppTask board description",
    scope: "доска (entity-level)",
    candidates: "описание доски",
    violation: "нет ссылки на папку проекта",
    passed: "ссылка есть",
    notChecked: "—",
    outcomeOK: "ссылка найдена",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  40: {
    sources: "AppTask board description",
    scope: "доска (entity-level)",
    candidates: "описание доски",
    violation: "нет краткого описания из ТЗ",
    passed: "описание достаточной длины",
    notChecked: "—",
    outcomeOK: "описание OK",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  41: {
    sources: "AppTask comments",
    scope: "комментарии task-level карточек",
    candidates: "комментарии с «?» или маркерами вопроса (вопрос, уточнить, обсудить, ждем ответ, непонятно)",
    violation: "вопрос-кандидат без ответа другого участника",
    passed: "ответ найден или нет вопросов-кандидатов",
    notChecked: "невозможно связать вопрос и ответ (автор/время)",
    outcomeOK: "0 вопросов-кандидатов → «по найденным маркерам не найдено»",
    outcomePartial: "связь вопрос→ответ эвристическая → PARTIAL, не уверенный OK",
    outcomeSkip: "—",
    automationLevel: "PARTIAL",
    autoProvable: "частично",
    reportWording: "проверено частично; показать stats: комментарии, «?», кандидаты",
  },
  42: {
    sources: "AppTask title, description, comments",
    scope: "активные task-level карточки",
    candidates: "текст с маркерами: уточнить, обсудить, ждем ответ, ждём ответ, непонятно",
    violation: "маркер в активной карточке без закрывающего комментария",
    passed: "маркеров нет или закрыты",
    notChecked: "—",
    outcomeOK: "0 совпадений → показать маркеры и поля поиска",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "TEXT_MARKER",
    autoProvable: "частично",
    reportWording: "по фиксированным текстовым маркерам",
  },
  43: {
    sources: "AppTask status, assignees",
    scope: "карточки на этапе проверки / QA",
    candidates: "текущий статус ∈ review/QA",
    violation: "исполнитель (тестировщик) не назначен",
    passed: "назначен",
    notChecked: "—",
    outcomeOK: "0 задач на проверке",
    outcomePartial: "—",
    outcomeSkip: "—",
    automationLevel: "STRICT",
    autoProvable: "да",
  },
  44: {
    sources: "AppTask assignees; AppTask users API (blocked)",
    scope: "task-level с назначенным исполнителем",
    candidates: "назначения на исполнителей",
    violation: "исполнитель blocked в AppTask",
    passed: "исполнитель активен",
    notChecked: "источник «уволенные/неактивные» не подключён — только blocked users",
    outcomeOK: "нет blocked assignees",
    outcomePartial: "источник уволенных недоступен → PARTIAL + «Не проверено»",
    outcomeSkip: "users API недоступен",
    automationLevel: "SOURCE_UNAVAILABLE",
    autoProvable: "нет",
    reportWording: "требует ручной проверки списка уволенных",
  },
  45: {
    sources: "AppTask title; status (завершённые); Scrum ПВ (косвенно)",
    scope: "завершённые task-level для актов",
    candidates: "завершённые задачи",
    violation: "название не готово к акту",
    passed: "название OK",
    notChecked: "фактическое время и ПВ — отдельные правила, здесь не проверяются",
    outcomeOK: "0 завершённых или все OK по названию",
    outcomePartial: "проверено частично: только название",
    outcomeSkip: "—",
    automationLevel: "PARTIAL",
    autoProvable: "частично",
    reportWording: "время и ПВ — отдельные правила",
  },
};

/** Полная матрица доказательств для 45 контрактных проверок. */
export const CONTRACT_RULE_EVIDENCE: readonly ContractRuleEvidenceSpec[] =
  CONTRACT_CHECK_REGISTRY.map((entry) => {
    const spec = EVIDENCE_BY_NUM[entry.num];
    if (!spec) {
      throw new Error(`Missing evidence spec for contract check #${entry.num}`);
    }
    return {
      num: entry.num,
      title: entry.title,
      ruleIds: entry.ruleIds,
      ...spec,
    };
  });

export function getEvidenceSpecByNum(num: number): ContractRuleEvidenceSpec | undefined {
  return CONTRACT_RULE_EVIDENCE.find((s) => s.num === num);
}

export function getEvidenceSpecByRuleId(ruleId: string): ContractRuleEvidenceSpec | undefined {
  return CONTRACT_RULE_EVIDENCE.find((s) => s.ruleIds.includes(ruleId));
}

export function groupEvidenceByAutomationLevel(): Record<
  AutomationLevel,
  ContractRuleEvidenceSpec[]
> {
  const groups: Record<AutomationLevel, ContractRuleEvidenceSpec[]> = {
    STRICT: [],
    TEXT_MARKER: [],
    PARTIAL: [],
    SOURCE_UNAVAILABLE: [],
    MANUAL_REQUIRED: [],
  };
  for (const spec of CONTRACT_RULE_EVIDENCE) {
    groups[spec.automationLevel].push(spec);
  }
  return groups;
}
